create table public.posts (
 id bigint generated by default as identity primary key,
 author_id uuid not null references auth.users(id) on delete cascade,
 title text not null,
 slug text unique not null,
 excerpt text default '',
 content text not null,
 category text default 'Note',
 image_url text,
 published boolean default false,
 created_at timestamptz default now(),
 updated_at timestamptz default now(),
 published_at timestamptz
);

alter table public.posts enable row level security;

create policy "public can read published posts" on public.posts for select using (published=true or auth.uid()=author_id);
create policy "users can insert own posts" on public.posts for insert with check (auth.uid()=author_id);
create policy "users can update own posts" on public.posts for update using (auth.uid()=author_id) with check (auth.uid()=author_id);
create policy "users can delete own posts" on public.posts for delete using (auth.uid()=author_id);

-- Storage bucket for article images.
insert into storage.buckets (id,name,public) values ('post-images','post-images',true)
on conflict (id) do nothing;

create policy "authenticated users upload post images"
on storage.objects for insert to authenticated
with check (bucket_id='post-images');

create policy "public can read post images"
on storage.objects for select to public
using (bucket_id='post-images');

create policy "users can delete their post images"
on storage.objects for delete to authenticated
using (bucket_id='post-images' and owner_id=auth.uid());